apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-hello-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-hello-app
    spec:
      containers:
      - name: hello-app
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8080
